runtime: python27
entrypoint: gunicorn -b :$PORT main.app
api_version: 1
threadsafe: true

runtime_config: 
  python_version: 3

handlers:
- url: /
  script: main.app

libraries:
- name: MySQLdb
  version: "latest"

#[START env]
env_variables:
    # Replace user, password, database, project, and instance with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      mysql+pymysql://root:downing/stagingdb?unix_socket=/cloudsql/backend-staging:us-central1:stagingdb
    # SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:downing@127.0.0.1/stagingdb
    # app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://root:downing@127.0.0.1/stagingdb'

#[END env]

#[START cloudsql_settings]
# Replace project and instance with the values obtained  when configuring your
# Cloud SQL instance.
beta_settings:
    cloud_sql_instances: backend-staging:us-central1:stagingdb
#[END cloudslq_settings]