runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /$
  static_files: build/index.html
  upload: build/index.html

- url: /
  static_dir: build


#- url: /htmlPages/(.*\.html)
#  mime_type: text/html
#  static_files: \1
#  upload: (.*\.html)

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$

- ^(.*/)?.*/node_modules/.*$
- ^(node_modules/.*)


