runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /$
  static_files: index.html
  upload: index.html

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /www
  static_dir: www

- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /.*
  upload: index.html
  static_files: index.html

#- url: /admin/.*
#  script: admin.app
#  login: admin
#
#- url: /.*
#  script: not_found.app